const imageBase = "/images";

export const categories = [
  { name: "Amigurumi", subtitle: "Hilos y materiales", image: `${imageBase}/hilo-amigurumi.jpg` },
  { name: "Chenille", subtitle: "Suave y esponjoso", image: `${imageBase}/chenille.jpg` },
  { name: "Trapillo", subtitle: "Bolsos y decoración", image: `${imageBase}/trapillo.jpg` },
  { name: "Algodón", subtitle: "Natural y fresco", image: `${imageBase}/algodon.jpg` },
  { name: "Herramientas", subtitle: "Agujas y más", image: `${imageBase}/herramientas.jpg` },
  { name: "Accesorios", subtitle: "Detalles que enamoran", image: `${imageBase}/accesorios.jpg` },
];

export const products = [
  {
    id: "hilo-amigurumi",
    name: "Hilo Amigurumi",
    detail: "Círculo 125 g",
    category: "Amigurumi",
    brand: "Círculo",
    thickness: "Fino",
    price: 4.5,
    image: `${imageBase}/hilo-amigurumi.jpg`,
    badge: "Más vendido",
    colors: [
      { name: "Chantilly", code: "7563", hex: "#ead8ca", image: `${imageBase}/hilo-amigurumi.jpg` },
      { name: "Rosa suave", code: "3526", hex: "#f3a7bb", image: `${imageBase}/chenille-rosa.jpg` },
      { name: "Menta", code: "5745", hex: "#83c8b4", image: `${imageBase}/chenille-menta.jpg` },
    ],
  },
  {
    id: "chenille-amigurumi",
    name: "Chenille Amigurumi",
    detail: "100 g · Hebra 3 mm",
    category: "Chenille",
    brand: "Círculo",
    thickness: "Grueso",
    price: 6,
    image: `${imageBase}/chenille.jpg`,
    heroImage: `${imageBase}/chenille-detalle.jpg`,
    badge: "Nuevo",
    description: "Chenille 100% poliéster de alta calidad. Suave, esponjosa y perfecta para amigurumis, mantas, cojines y proyectos de bebé.",
    colors: [
      { name: "Chantilly", code: "7563", hex: "#c9a9df", image: `${imageBase}/chenille.jpg` },
      { name: "Lila Candy", code: "6000", hex: "#d68ec0", image: `${imageBase}/chenille-rosa.jpg` },
      { name: "Neo Mint", code: "5745", hex: "#80c9b1", image: `${imageBase}/chenille-menta.jpg` },
      { name: "Azul Bic", code: "2829", hex: "#52a6cf", image: `${imageBase}/chenille-azul.jpg` },
      { name: "Vainilla", code: "1114", hex: "#f1df9a", image: `${imageBase}/chenille-vainilla.jpg` },
    ],
  },
  {
    id: "trapillo-premium",
    name: "Trapillo Premium",
    detail: "500 g · Colores lisos",
    category: "Trapillo",
    brand: "Pantera",
    thickness: "Grueso",
    price: 4.25,
    image: `${imageBase}/trapillo.jpg`,
    colors: [
      { name: "Mostaza", code: "TP08", hex: "#d7a623", image: `${imageBase}/trapillo.jpg` },
      { name: "Rosa Pastel", code: "TP12", hex: "#dfa5ad", image: `${imageBase}/chenille-rosa.jpg` },
    ],
  },
  {
    id: "algodon-mercerizado",
    name: "Algodón Mercerizado",
    detail: "100 g · Brillante",
    category: "Algodón",
    brand: "Alize",
    thickness: "Súper fino",
    price: 2.75,
    image: `${imageBase}/algodon.jpg`,
    colors: [
      { name: "Turquesa", code: "AM21", hex: "#11abc7", image: `${imageBase}/algodon.jpg` },
      { name: "Coral", code: "AM14", hex: "#ef7d53", image: `${imageBase}/algodon.jpg` },
    ],
  },
  {
    id: "crochet-soft",
    name: "Crochet Soft",
    detail: "100 g · Algodón mate",
    category: "Algodón",
    brand: "Alize",
    thickness: "Medio",
    price: 3.85,
    image: `${imageBase}/hilo-amigurumi.jpg`,
    colors: [{ name: "Natural", code: "CS01", hex: "#d9c3a9", image: `${imageBase}/hilo-amigurumi.jpg` }],
  },
  {
    id: "chenille-bebe",
    name: "Chenille Bebé",
    detail: "100 g · Extra suave",
    category: "Chenille",
    brand: "Pantera",
    thickness: "Grueso",
    price: 5.5,
    image: `${imageBase}/chenille-rosa.jpg`,
    colors: [{ name: "Rosa", code: "CB04", hex: "#e3a1be", image: `${imageBase}/chenille-rosa.jpg` }],
  },
  {
    id: "kit-agujas",
    name: "Kit de agujas ergonómicas",
    detail: "6 medidas",
    category: "Herramientas",
    brand: "Madejitas",
    thickness: "Accesorio",
    price: 12.5,
    image: `${imageBase}/herramientas.jpg`,
    colors: [{ name: "Pastel", code: "KIT06", hex: "#c9a7db", image: `${imageBase}/herramientas.jpg` }],
  },
  {
    id: "ojitos-seguridad",
    name: "Ojitos de seguridad",
    detail: "Set de 30 piezas",
    category: "Accesorios",
    brand: "Madejitas",
    thickness: "Accesorio",
    price: 3.25,
    image: `${imageBase}/accesorios.jpg`,
    colors: [{ name: "Negro", code: "OS30", hex: "#252126", image: `${imageBase}/accesorios.jpg` }],
  },
];

export const money = (value) => `$${value.toFixed(2)}`;
